-- +goose Up
CREATE TABLE NODE_CONTENT(
	NODE_CONTENT_ID TEXT PRIMARY KEY,
	BACKGROUND_COLOR TEXT,
	CREATED_TIMESTAMP BIGINT,
	MODIFIED_TIMESTAMP BIGINT,
	FREEMIND_ID TEXT,
	URL TEXT,
	STYLE TEXT,
	TEXT TEXT,
	NOTE TEXT,
	ICONS TEXT,
	FONT_NAME TEXT,
	FONT_BOLD INTEGER,
	FONT_SIZE INTEGER);
	
-- +goose Down
DROP TABLE NODE_CONTENT;