-- +goose Up
CREATE TABLE NODE_RELATION(
	PARENT_NODE_ID TEXT NOT NULL REFERENCES NODE,
	CHILD_NODE_ID TEXT NOT NULL REFERENCES NODE,
	CHILD_NODE_KEY TEXT NOT NULL);
				
-- +goose Down
DROP TABLE NODE_RELATION;