-- +goose Up
CREATE TABLE BRANCH(
	BRANCH_ID TEXT PRIMARY KEY,
	BRANCH_NAME TEXT,
	DOCUMENT_ID TEXT NOT NULL REFERENCES DOCUMENT,
	COMMIT_ID TEXT NOT NULL REFERENCES COMMITS,
	CREATED_TIMESTAMP bigint NOT NULL);
				
-- +goose Down
DROP TABLE BRANCH;
