-- +goose Up

-- revision is like git tag
CREATE TABLE REVISION(
	REVISION_ID TEXT PRIMARY KEY,
	DOCUMENT_ID TEXT NOT NULL REFERENCES DOCUMENT,
	CREATED_TIMESTAMP bigint NOT NULL,
	COMMENT VARCHAR(255),
	COMMIT_ID TEXT NOT NULL REFERENCES COMMITS);
				
-- +goose Down
DROP TABLE REVISION;
