-- +goose Up
CREATE TABLE DOCUMENT(
	DOCUMENT_ID TEXT PRIMARY KEY,
	DOCUMENT_NAME TEXT, 
	FORMAT_VERSION TEXT,
	CREATED_TIMESTAMP bigint NOT NULL,
	MAIN_BRANCH_ID TEXT NOT NULL REFERENCES BRANCH);
				
-- +goose Down
DROP TABLE DOCUMENT;
