// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql"
)

type BRANCH struct {
	BranchID         string
	BranchName       sql.NullString
	DocumentID       string
	CommitID         string
	CreatedTimestamp int64
}

type COMMIT struct {
	CommitID         string
	RootNodeID       string
	ParentCommitID   sql.NullString
	CreatedTimestamp int64
}

type DOCUMENT struct {
	DocumentID       string
	DocumentName     sql.NullString
	FormatVersion    sql.NullString
	CreatedTimestamp int64
	MainBranchID     string
}

type NODE struct {
	NodeID        string
	NodeContentID string
}

type NODECONTENT struct {
	NodeContentID     string
	BackgroundColor   sql.NullString
	CreatedTimestamp  sql.NullInt64
	ModifiedTimestamp sql.NullInt64
	FreemindID        sql.NullString
	Url               sql.NullString
	Style             sql.NullString
	Text              sql.NullString
	Note              sql.NullString
	Icons             sql.NullString
	FontName          sql.NullString
	FontBold          sql.NullInt64
	FontSize          sql.NullInt64
}

type NODERELATION struct {
	ParentNodeID string
	ChildNodeID  string
	ChildNodeKey string
}

type REVISION struct {
	RevisionID       string
	DocumentID       string
	CreatedTimestamp int64
	Comment          sql.NullString
	CommitID         string
}
