-- name: RootNodeByDocumentName :one
SELECT ROOT_NODE_ID
FROM DOCUMENT
JOIN BRANCH ON BRANCH.BRANCH_ID = DOCUMENT.MAIN_BRANCH_ID
JOIN COMMITS ON COMMITS.COMMIT_ID = BRANCH.COMMIT_ID
WHERE DOCUMENT_NAME = ?