// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: rootNode.sql

package queries

import (
	"context"
	"database/sql"
)

const rootNodeByDocumentName = `-- name: RootNodeByDocumentName :one
SELECT ROOT_NODE_ID
FROM DOCUMENT
JOIN BRANCH ON BRANCH.BRANCH_ID = DOCUMENT.MAIN_BRANCH_ID
JOIN COMMITS ON COMMITS.COMMIT_ID = BRANCH.COMMIT_ID
WHERE DOCUMENT_NAME = ?
`

func (q *Queries) RootNodeByDocumentName(ctx context.Context, documentName sql.NullString) (string, error) {
	row := q.db.QueryRowContext(ctx, rootNodeByDocumentName, documentName)
	var root_node_id string
	err := row.Scan(&root_node_id)
	return root_node_id, err
}
