// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: stats.sql

package queries

import (
	"context"
)

const countOfDocuments = `-- name: CountOfDocuments :one
SELECT COUNT(*) FROM DOCUMENT
`

func (q *Queries) CountOfDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOfDocuments)
	var count int64
	err := row.Scan(&count)
	return count, err
}
