-- name: CreateCommit :exec
INSERT INTO COMMITS(
	COMMIT_ID,
	ROOT_NODE_ID,
	PARENT_COMMIT_ID,
	CREATED_TIMESTAMP) 
VALUES(?, ?, ?, ?);

-- name: CreateBranch :exec
INSERT INTO BRANCH(
	BRANCH_ID,
	BRANCH_NAME,
	DOCUMENT_ID,
	COMMIT_ID,
	CREATED_TIMESTAMP)
VALUES(?, ?, ?, ?, ?);

-- name: CreateRevision :exec
INSERT INTO REVISION(
	REVISION_ID,
	DOCUMENT_ID,
	CREATED_TIMESTAMP,
	COMMENT,
	COMMIT_ID)
VALUES(?, ?, ?, ?, ?);

-- name: CreateDocument :exec
INSERT INTO DOCUMENT(
	DOCUMENT_ID,
	DOCUMENT_NAME, 
	FORMAT_VERSION,
	CREATED_TIMESTAMP,
	MAIN_BRANCH_ID)
VALUES(?, ?, ?, ?, ?);